### ISSUE TITLE
Segmentation filter dropdown

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#24]
When I select "SheffieldLab" under Provider, it takes me to:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by oddodaoddo** [comment]
Should work properly now with latest commit (https://github.com/databio/episb-hub/commit/8101aeef8afdc13b2001d7d1a28ec4088c3c6079)

**Comment by nsheff** [comment]
Yes that is working, but now when you try to select an experiment, it resets the segmentation.

can you do a complete test through the whole thing?

**Comment by oddodaoddo** [comment]
It resets because the next step is not implemented (the slider rule or whatever we want).
