### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#26]
change the app theme so it either matches or is clearly distinct from the docs theme. right now it's sort of similar, but just non-centered navbar, which is strange

**Comment by aaron-gu** [comment]
The docs do not display correctly if the window is narrowed 
![screen shot 2019-01-29 at 12 21 15 am](https://user-images.githubusercontent.com/32209687/51885962-cbd15300-235b-11e9-9210-8fd593715c18.png)

It might fall under this issue for reformatting the docs theme.

**Comment by nsheff** [comment]
fixed by new mkdocs theme.
