### ISSUE TITLE
region query broken again

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#28]
http://episb.org/segment/json/1/54321/500000

```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by oddodaoddo** [comment]
Do you mean http://episb.org/region/1/54321/500000 and http://episb.org/api/v1/region/1/54321/500000? They are both working for me.

**Comment by oddodaoddo** [comment]
Wrong URL used in ticket.

**Comment by nsheff** [comment]
that was the URL that the HTML form was sending me to... it is now sending me to the correct URL, so there must have been a container update or something that fixed this.

**Comment by nsheff** [comment]
I think maybe soon we should start developing on a dev branch and then releasing with version tags. it would prevent this kind of error. Maybe we'll aim to start doing that at the release 0.2 milestone.
