### ISSUE TITLE
default subscription

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#29]
Related to #5.

The hub should start with a set of default providers (in this case, provider.episb.org) already loaded in the subscription interface.

These providers should be used for all queries; for example, the region query right now is not working, but if it were working it should use existing providers.

**Comment by oddodaoddo** [comment]
God Flask sucks. Why is session management so difficult? Working on this.

**Comment by oddodaoddo** [comment]
OK - finally fixed properly.

**Comment by nsheff** [comment]
:trophy: looks good.

is this configurable? For example, when I make a new hub, where do I put the location of the default providers for my hub? can you document that?

**Comment by oddodaoddo** [comment]
Not yet. I will add that at some point after I am done with the important queries in the hub.
