### ISSUE TITLE
"Live" slider value updating

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/episb-hub#30]
A little suggestion: if you change the `onchange` attribute to `oninput` in the line linked below, the value will update continuously, which is much more helpful than displaying it after the release.
https://github.com/databio/episb-hub/blob/d04504fa3c82b9565ac270de9f77497a44f32d01/templates/home.html#L114

**Comment by oddodaoddo** [comment]
Wonderful, will do!

**Comment by oddodaoddo** [comment]
My problem is that some of these experiments (a lot of them?) have values between 0 and 1 as floating numbers. Doing the above change does not make any difference in that case. Do I need to normalize these to bring them into the 0 to 100 range?

**Comment by michalstolarczyk** [comment]
To make it possible to select floats you can set another attribute `step` to whatever value, like 0.1

**Comment by oddodaoddo** [comment]
Done - thanks!
