### ISSUE TITLE
Example API queries

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#32]
Can you add working examples (clickable URLs) for all API points listed in the [data provider api](http://code.databio.org/episb/provider-api/) ?

**Comment by oddodaoddo** [comment]
Just to confirm - this is in addition to the Python code below every API explanation? Just a link with the actual example query to provider.episb.org/episb-provider/<API call here> - correct?

**Comment by nsheff** [comment]
Right -- I want users to be able to test these queries out with a click (not having to fire up python)

**Comment by nsheff** [comment]
we already have some here: http://code.databio.org/episb/howto-query-provider/

**Comment by oddodaoddo** [comment]
Got it.

**Comment by oddodaoddo** [comment]
https://github.com/databio/episb-hub/tree/Issue-32

**Comment by oddodaoddo** [comment]
Need to include new API points (.gz matrix for example) and update some that now accept parameters.

**Comment by oddodaoddo** [comment]
Merged into dev, closing.

**Comment by nsheff** [comment]
I still don't see examples live...do you need to update the docs site?

**Comment by oddodaoddo** [comment]
It is all in the dev branch. I was not sure what the process is for dev branch -> live docs

**Comment by nsheff** [comment]
got it! thanks. I think for now can you pretty much update at will. maybe that will change in the future
