### ISSUE TITLE
BED file returns

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#34]
any query that returns regions or segments should have an option to return a BED format file.

**Comment by nsheff** [comment]
given that format can be either html, json, or bed for some queries, maybe we should have a universal `?format= flag` that can be added to the end of the query URL. this is the way the API for [e-utilities at NCBI](https://www.ncbi.nlm.nih.gov/books/NBK25500/#chapter1.Downloading_Full_Records) works.

**Comment by oddodaoddo** [comment]
Makes sense. Would not be a big deal to implement.

**Comment by oddodaoddo** [comment]
This issue belongs to the provider, not the hub.

**Comment by oddodaoddo** [comment]
This [commit](https://github.com/databio/episb-provider/commit/30545ffb57936d607d3c39926c1561f57514b124) implements this issue on the provider.

**Comment by nsheff** [comment]
please explain how to use this; I guess it would be here: http://code.databio.org/episb/provider-api/ ?

**Comment by oddodaoddo** [comment]
OK, the following query is an example of what is returned now:
`http://provider.episb.org/episb-provider/segments/get/fromSegment/1/10000/30000?format=bed

**Comment by nsheff** [comment]
that looks correct. and it reminds of something I meant to ask you about: https://github.com/databio/episb-hub/issues/55

**Comment by oddodaoddo** [comment]
Ok - this is live.

**Comment by nsheff** [comment]
> It is documented now in http://code.databio.org/episb/provider-api/ - search for "format=bed" in the page.

I cannot find any documentation on this.

**Comment by oddodaoddo** [comment]
It looks like someone reverted the changes. I also had the API query examples for each API point as per your request deployed - they were up for days but now they are gone as well.

**Comment by nsheff** [comment]
probably me -- I"m the only other one change those pages. but probably they are just overridden at the render level, not in the source. I can try to remake them.

**Comment by nsheff** [comment]
this should do it! https://github.com/databio/code.databio.org/commit/4bbe4b9de84f3ca9c5efc9d3ccef667147d5e7df

**Comment by oddodaoddo** [comment]
This is now live.
