### ISSUE TITLE
Segmentation filter extra rules

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#35]
Each "Rule" includes not only the operation and value, but the experiment.  Adding a rule should therefore add a new experiment select box.

**Comment by aaron-gu** [comment]
I'm not sure I completely understand the purpose of the segmentation filter and experiments. Does adding more experiments just return more search results? Can an experiment have more than one rule, like <50 and >20?

**Comment by nsheff** [comment]
Read this: http://code.databio.org/episb/howto-query-provider/#query-segmentation-filter

Each rule is an experiment and a condition. as it stands now, you can only add rules for 1 experiment.

**Comment by oddodaoddo** [comment]
Maybe a better way to think about this is:

1) each experiment has annotation values (within a certain range)
2) for each experiment you can say give me all annotations equal to <value> or >= <value> [AND/OR <= <value>]

In practice this means that you could have up to three selector boxes for one experiment: for example, you may want all annotations in a range [a,b] AND all annotations with value=c. 

You could want the above for multiple experiments.

@nsheff : is this an accurate description of what this query is looking to achieve?

**Comment by nsheff** [comment]
yes

**Comment by oddodaoddo** [comment]
In fact, you could have any number of selectors per experiment.

For example, for experiment1, you could want all values between 0.1 and 0.3 AND all values equal to 0.5 AND all values between 0.6 and 0.7. For experiment2 you may only want all values between 0.2 and 0.7. So on and so on.

**Comment by oddodaoddo** [comment]
@aaron-gu : The segmentation filter interface issue is assigned to you - do you want me to give it a shot with what you started on? :smile:

**Comment by aaron-gu** [comment]
Yep go ahead. I will also work on it some tonight and tomorrow afternoon.

**Comment by aaron-gu** [comment]
This is more complex than I thought. We need to make AND and OR statements for the cases like:
- 35 <= x <= 70 (AND case)
- x < 75, x = 85 (OR case)
- and combinations of the above (more ORs stringed together)

The AND rules also need to be checked for validity, as you cannot have something like 35 <= x <= 25. I don't know if it's better to check this on the client side or the server side.

For now, I will give each experiment the ability to add unlimited rules without checking them, and also implement the button to add multiple experiments.

**Comment by oddodaoddo** [comment]
Yup, I thought it would be complex. I would say check everything you can on client side because you can communicate with the user at that moment.

**Comment by aaron-gu** [comment]
The button to add multiple experiments is implemented, but there is an issue due to the page reloading after selecting an experiment. Only one experiment can be populated into the form at a time, and adding more experiments will just show a dropdown of 1 item, which is the current experiment. @oddodaoddo can you take a look into dynamically loading the form items?

**Comment by oddodaoddo** [comment]
Hmm, I see. Let me think about this a bit.

**Comment by oddodaoddo** [comment]
I think what I am going to do is pass you a list of tuples, where each tuple will be (experiment_name, (experiment_range_min, experiment_range_max)). This way you can add experiments and conditions in the interface (on the JS side) and once the search button is clicked, send me all the info in the form).

**Comment by oddodaoddo** [comment]
@aaron-gu : I am not passing you a list of (exp_name, min, mid, max, step) values so you can have better control during the selection process (without going back to flask). Does this work for you?

**Comment by oddodaoddo** [comment]
The requirements for this issue are somewhat vague on that. In my mind, the segmentation is hard-coded and we are only looking at the experiments within that segmentation (@nsheff?). So, for such a segmentation the list of quintuples is not that bad. Obviously, if changing the segmentation (or how about the provider as well) - allowing you to mix and match things from multiple providers AND segmentations - we would have to re-think the approach. I am happy to do whatever is best practice :)

**Comment by oddodaoddo** [comment]
I guess what I am trying to say is - once a provider/segmentation has been chosen, we vary the experiment subset that can be added. For this I think it is appropriate to pass on a list of experiments with their min/max/mid/step values - this will give you full control on the front end to not have to go back to flask every time an experiment is added to list.

**Comment by oddodaoddo** [comment]
@aaron-gu What do you think? You want to give this a crack?

**Comment by aaron-gu** [comment]
Sure, I think it will work.

**Comment by aaron-gu** [comment]
Actually, I think a dictionary input will make it easier. Right now I am populating the selection panel with experiment names and getting their value when they are clicked. Then, since it is a list, I have to do a linear scan to find the correct experiment and get the experiment details. I think the best format for the dictionary would be experiment names mapping to a list or tuple of the experiment values.

**Comment by oddodaoddo** [comment]
Cool - I can do that - a dictionary keyed by experiment name and each value is a quartuple (min, mid, max, step).

**Comment by oddodaoddo** [comment]
Ok @aaron-gu - try now.

**Comment by aaron-gu** [comment]
The page is fully functional now. There are a few minor things to be checked like validity of ANDs. Do you want to start implementing the backend now, and let me know what might need to be changed to work with flask better?

**Comment by oddodaoddo** [comment]
Yes, thanks!! The site is down (again) - I think we ran out of space (again) ;)

**Comment by oddodaoddo** [comment]
It is not a space issue - something about the new home.html template is causing flask to vomit.

**Comment by oddodaoddo** [comment]
Ok - fixed it. @aaron-gu : when I try to add experiments, the >= and <= are not visible. See screenshot (Firefox/FreeBSD). 
![screenshot](https://user-images.githubusercontent.com/7661532/52521410-e2718700-2c44-11e9-83f5-bb830bd6d8c9.jpg)

**Comment by aaron-gu** [comment]
I just pushed a change that increases the width of the dropdown box. Does that fix it?

**Comment by oddodaoddo** [comment]
@aaron-gu : That worked. Now, for a different question: I think whatever is getting submitted to the form when "Search" is clicked is wrong. See attached screenshot and what I am getting as form keys and values.

![screenshot](https://user-images.githubusercontent.com/7661532/525['Filter', 'selected_provider', 'segmentation_name', 'slider2', 'slider3', 'experiment_name', 'slider1', 'slider4']
Filter=ge
selected_provider=http://provider.episb.org/episb-provider
segmentation_name=DHS
slider2=0.87
slider3=1
experiment_name=http://provider.episb.org/episb-provider!DHS!HCFaa
slider1=0.5
slider4=0.29
64469-4a090d00-2dd2-11e9-93d8-5acb7418432e.jpg)

**Comment by oddodaoddo** [comment]
@aaron-gu : I am going to start looking at the above issue and try to figure out what's going on, if you don't have the time. Thanks! :smile:

**Comment by aaron-gu** [comment]
Is the problem that some filters <, > are not in the submitted form? Also, I wonder if there is a way to group the sliders together when a form is submitted.

**Comment by oddodaoddo** [comment]
I think not all experiments are coming back to the form, the sliders are OK since they are marked with numbers but we need a way to know which sliders with which experiment :smile:

**Comment by aaron-gu** [comment]
After talking to Nathan, I'm going to make some changes to the core logic behind the current segmentation filter. I will remove the AND/OR rules, and just leave "add experiment". Each experiment will have the name "experiment0/1/2" and a corresponding "operator0/1/2" and "value0/1/2". Then in flask we should be able to use a for-loop to get each filter.

**Comment by aaron-gu** [comment]
Also I think the issue with the form from before was that all of the operators and experiments were getting the same "name" attribute, which is passed to flask when the form is submitted.

**Comment by oddodaoddo** [comment]
@aaron-gu : I noticed a code commit - working on this now. Thanks!

**Comment by oddodaoddo** [comment]
This query will require a modification to the episb-provider query to get all annotation values for an experiment. We can modify the episb-provider to take in the filter so that we return the data filtered at the source (in elastic).

**Comment by oddodaoddo** [comment]
> This query will require a modification to the episb-provider query to get all annotation values for an experiment. We can modify the episb-provider to take in the filter so that we return the data filtered at the source (in elastic).

Functionality implement with this code commit: https://github.com/databio/episb-provider/commit/86c73bdad12e1d8754567c88d734a0269844cca1. After some testing, I will be able to finish the segmentation filter.

**Comment by oddodaoddo** [comment]
Whef! What a beast! I committed the main code to read in the data, consolidate multiple operators (e.g. >=0.5 && >=0.6 && >=0.7) etc. etc. Right now it spits the raw json back onto the console. I will finish the presentation layer tomorrow :smile:

**Comment by oddodaoddo** [comment]
This is the [commit](74cbfce19a769a387972f4e36a08f7dbc21ad570)  for this issue

**Comment by aaron-gu** [comment]
It looks like the filter works for >= && <=, but is not returning the right results for just a single operator. Maybe the default min/max needs to be set to the experiment min/max values.

**Comment by oddodaoddo** [comment]
Can you throw in a screenshot? I just ran it for a single operator and it works fine for me.

**Comment by aaron-gu** [comment]
Nevermind, I think I mistakenly saw some values. Sorry!

**Comment by oddodaoddo** [comment]
I consider this issue finished. It has been deployed for a week or more now and nobody has complained :smiley:
