### ISSUE TITLE
Refining subscription interface

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#36]
- [ ] It should be possible to remove a data provider ("unsubscribe").

- [x] It should also be possible to view more information than the 3 elements currently visible in the interface...all of the info in [the provider interface](http://provider.episb.org/episb-provider/provider-interface) should be either visible, or able to be seen in that interface with a 'details' button or something.

**Comment by oddodaoddo** [comment]
One of the above is implemented in Issue-36 branch. Working on the other point.
