### ISSUE TITLE
hub should have configurable default providers

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#37]
when I make a new hub, where do I put the location of the default providers for my hub? can you document that?

_Originally posted by @nsheff in https://github.com/databio/episb-hub/issues/29#issuecomment-457277613_

**Comment by oddodaoddo** [comment]
This was implemented in the yaml version of a hub config file.

**Comment by nsheff** [comment]
is this documented anywhere? I mean, instructions for this config file. I would expect to read it on this page: 

http://code.databio.org/episb/howto-build-hub/
