### ISSUE TITLE
Implement a "provider subscriptions" web GUI in the hub

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#5]
The hub needs a way for a user to *link* external data providers by providing a `provider interface` file (https://github.com/databio/episb-provider/issues/6). This should just be a text field with a submit button where the user submits a URL (similar to the way UCSC track hubs work). That URL should point to the above `design interface` file (or API point, perhaps?). The hub then parses this information into a form that it knows what data is availble from which provider, and how to query it.

Armed with information from one or more provider design interfaces, the hub is prepared to render a web UI to allow a user to make queries.

**Comment by oddodaoddo** [comment]
Done.

**Comment by nsheff** [comment]
http://episb.org/subscriptions: **Internal Server Error**

**Comment by oddodaoddo** [comment]
Try now. You went to a page directly (only / would set the session cookie). Now they all check for existence of session cookie first.
