### ISSUE TITLE
episb.org down

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#53]
Since 2pm, so it's been 4 hours...

502 Bad Gateway
nginx/1.15.3

**Comment by oddodaoddo** [comment]
Hey Dr. Sheffield, we had the meeting and then it took me 3 hours to get home etc. so... Anywhoo, it is back up.

**Comment by nsheff** [comment]
cool -- what happened?

**Comment by oddodaoddo** [comment]
No idea! :smile: - I restarted the docker container and it is working now. It is strange (and unsettling)...

**Comment by nsheff** [comment]
Down again.

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by oddodaoddo** [comment]
Sorry, this time it was me. I brought down the docker container to test the matrix query in the console. Should be back up now.
