### ISSUE TITLE
making human-readable IDs

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#55]
Right now our IDs are like hashes, looking like: "BroadHmm::36af55ad-b62f-40fb-8bfc-0dbb05169306"

Can we instead use something that would be meaningful to a human? Like:

"BroadHmm::Segment1539"

This will be much easier to deal with in the future as people start to need to refer to these, for example, in a paper.

**Comment by oddodaoddo** [comment]
We can. We use UUIDs which are easy to auto-generate. I can decide on some large number - say, 100,000 (just kidding, something larger than that) and generate a random number when creating the segment ID.

**Comment by nsheff** [comment]
would it be too much trouble to have them go in order? Maybe not worth it...seems easier becuase then there's no clashes and the order is meaningful.

**Comment by oddodaoddo** [comment]
The IDs are assigned at the moment a segmentation is created. For them to go in order, I would have to keep track of the last one loaded. Not a big deal, I would say, we could stash counter this somewhere.

**Comment by nsheff** [comment]
a segmentation should be created all at once, shouldn't it?

Anyway it would be good anyway for the Segmentation object to keep track of how many Segments it has. when creating a new one it increments this and uses it to assign the ID to the new Segment.

**Comment by oddodaoddo** [comment]
Yes, you are right. Segment names should only be unique inside a segmentation, not across ALL segmentations.

**Comment by nsheff** [comment]
of course

**Comment by oddodaoddo** [comment]
Yup. Right now they are unique per provider. If someone were to run their own provider and load their own segmentation - the IDs would be randomly generated UUIDs prefixed by the segmentation name and "::". However, the UUIDs are not checked against any other provider - hence, it doesn't really matter that a random UUIDs is used anyway.

**Comment by nsheff** [comment]
ok then I think it's clear we should do within-provider uniqueness only, with human readable increments of the form "SegmentXXXX", and have the segmentation remember how many segments it contains.

any questions?

**Comment by oddodaoddo** [comment]
Nope, we agree.

**Comment by oddodaoddo** [comment]
I am going to restart elastic for the matrix query. We may need to re-load the experiments and if this is the case, I will implement this change on the fly.

**Comment by oddodaoddo** [comment]
The new data is being loaded with this feature turned on.

**Comment by nsheff** [comment]
awesome.

this will ruin all of our example URLs though :)

**Comment by oddodaoddo** [comment]
Oh well - I will fix :smiley:
