### ISSUE TITLE
dev container isn't building

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#56]
when I build and run this container off the dev branch, I get a 502 gateway error. But when I build and run it off the master branch, it works. so, something is broken in the dev container...

**Comment by oddodaoddo** [comment]
Yup, that's was the problem. Oddly enough, episb.org was running the dev branch. I can run the dev branch locally via ```FLASK_APP="main.py" flask run``` though.

**Comment by nsheff** [comment]
is this fixed?

**Comment by oddodaoddo** [comment]
Yes. It was missing a requirement (PyYAML) in requirements.txt. I am going to push the changes now. The site is running dev version now (you can check by going to "subscriptions" where it is listing more info, like you requested in one of the tickets :smile:
