### ISSUE TITLE
simplify dev dockerfile instructions

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#58]
Hi @aaron-gu 
you created Dockerfile_dev to allow mounting an app for development. Actually, you can simply mount over the the `/app` folder in the same container...

See how I did it here: https://github.com/databio/episb-provider/tree/dev/episb-api

to develop you don't need a different container... just use `v $(pwd):/app`.

Can you update instructions here accordingly? Remove extra dockerfile etc

**Comment by aaron-gu** [comment]
What does /start-reload.sh do?

**Comment by nsheff** [comment]
https://medium.com/@williamhayes/fastapi-starlette-debug-vs-prod-5f7561db3a59

shouldn't matter for the current dockerfile, which is using flask instead of fastapi

**Comment by nsheff** [comment]
in other words, for the flask case, you keep what you have:

```
-e FLASK_APP=main.py -e FLASK_DEBUG=1 episb flask run --host=0.0.0.0 --port=80
```
